# Generated by Django 4.0.5 on 2022-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_home_page_btn_alter_home_cv_btn'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
