# Generated by Django 4.0.6 on 2022-07-14 18:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('page', '0003_about_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='sub_title',
        ),
        migrations.AddField(
            model_name='about',
            name='auth_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='about',
            name='content',
            field=wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('type', wagtail.core.blocks.ChoiceBlock(choices=[('h2', 'Header 2'), ('h3', 'Header 3'), ('h4', 'Header 4')])), ('title', wagtail.core.blocks.CharBlock(max_length=255))])), ('Rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(max_length=50, required=False))]))], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
