# Generated by Django 4.0.6 on 2022-07-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_rename_text_about_sub_title_about_auth_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='salutation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='sub_title',
            field=models.CharField(max_length=255),
        ),
    ]
