# Generated by Django 4.0.5 on 2022-07-09 12:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('test_text', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=100)),
                ('project_bio', wagtail.core.fields.RichTextField()),
                ('content', wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('type', wagtail.core.blocks.ChoiceBlock(choices=[('h2', 'Header 2'), ('h3', 'Header 3'), ('h4', 'Header 4')])), ('title', wagtail.core.blocks.CharBlock(max_length=255))])), ('image', wagtail.core.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(max_length=50, required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.TextBlock())])), ('terminal', wagtail.core.blocks.StructBlock([('code', wagtail.core.blocks.CharBlock(max_length=255))])), ('Rich_text', wagtail.core.blocks.RichTextBlock())])),
                ('show_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
