# Generated by Django 4.0.5 on 2022-07-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('project', '0002_projecttag_remove_project_test_text_project_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='tag_image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
            preserve_default=False,
        ),
    ]
