# Generated by Django 4.0.5 on 2022-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('project', '0003_alter_projecttag_tag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
