# Generated by Django 4.0.5 on 2022-07-09 14:19

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('project', '0004_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='category.category'),
        ),
    ]
