# Generated by Django 4.0.5 on 2022-07-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_category_project_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
